### ISSUE TITLE
read-flight ignores IGC hemispheres

### ISSUE THREAD

**Issue by twpayne** [Turbo87/aeroscore#2]
The IGC reader in [`read-flight.ts`](https://github.com/Turbo87/aeroscore/blob/master/src/read-flight.ts) ignores the latitude and longitude hemispheres in IGC B records, with obvious consequences.

**Comment by Turbo87** [comment]
@twpayne thanks for reporting this. the implementation in `read-flight.ts` was just a quick prototype to allow me to iterate on the scoring code. by now I've extracted a more full-featured IGC files parser into https://github.com/Turbo87/igc-parser and will reuse that from now on. obviously that one works with southern and western coordinates too now 😉
