### ISSUE TITLE
Make aeroscore more tolerant against bad OGN coverage

### ISSUE THREAD

**Issue by dspreitz** [Turbo87/aeroscore#27]
When the OGN coverage at the turnpoint is not sufficient, aeroscore misses turn points of contestants and stops scoring.
This is in theory correct, but unpractical.
Based on certain flexible metrics the turnpoint area could be virtually enlarged to compensate for bad OGN coverage and count the turn point as reached, even though no OGN data proving this was received.
Needs more details to be imlemented.

**Comment by Turbo87** [comment]
closing in favor of #26 

sorry 🙈
