### ISSUE TITLE
Provide glidertracker status info via command line interface

### ISSUE THREAD

**Issue by dspreitz** [Turbo87/aeroscore#79]
To monitor the status of the glidertracker a command line tool with following capabilities would be nice:
- Executeable via CLI / shell script
- Returns following status info and then exits:
   x Connection to GT successfull: integer: 1 = success, 0 = failure
   x Data (AC positions) received: integer: 1 = success, 0 = failure
   x Data (AC positions) unserstandable / parseable: integer: 1 = success, 0 = failure
   x Number of users (taken from debug dialog): integer
   x Server load: real
   x RX: real
   x TX: real
   x Memory: real
- Exit status should be 0 for successfull program execution (irrespective the GT status info) and 1 in case of errors

**Comment by Turbo87** [comment]
with https://nodeping.com/reports/checks/r5kndvxu-lwjq-4xd1-8tbw-tsekn6swtlg9 working, is this still needed?

**Comment by Turbo87** [comment]
closing as we no longer rely on Glidertracker for ogn-web-viewer
